Repository schmitty890/homestead, pull requests merged in 2018-06, with the labels that each got.

#106 event limit and order
  db/seeds.js
  routes/html-routes.js
Labels: back end

#105 faq dynamic json loading
  data/faq.json
  routes/html-routes.js
  views/faq.handlebars
Labels: back end

#104 adding 404 route after all other routes
  server.js
  views/404.handlebars
Labels: back end

#110 Account profile partials
  views/account.handlebars
  views/partials/profile.handlebars
  views/partials/profile_list.handlebars
  views/partials/profile_nav.handlebars
Labels: back end

#131 root file path added
  views/layouts/main.handlebars
  views/partials/header.handlebars
Labels: front end

#133 adding classified seeds so dev is easier
  db/seeds.js
Labels: database

#135 setting up classifieds
  views/classifieds.handlebars
  views/partials/nav.handlebars
Labels: back end

#146 Classifieds landing page
  routes/html-routes.js
  views/classifieds.handlebars
Labels: back end

#163 changing font awesome icons and color
  data/hp-classifieds.json
  scss/partials/_classes.scss
  views/partials/classifieds_homepage.handlebars
Labels: front end

#164 weather widget
  package-lock.json
  package.json
  public/assets/js/weather.js
  routes/api-routes.js
  scss/partials/_classes.scss
  views/partials/header.handlebars
  views/partials/nav.handlebars
Labels: back end, front end

#169 removing sub cats and wrapping icon in link tag
  data/hp-classifieds.json
  views/partials/classifieds_homepage.handlebars
Labels: back end

#168 classified nav dropdown links
  views/partials/nav.handlebars
Labels: back end

#171 superscript degree symbol and F
  public/assets/js/weather.js
Labels: front end

#181 date class for form elements
  public/assets/js/form.js
  views/partials/post_event_partial.handlebars
  views/partials/post_res_partial.handlebars
Labels: front end

#189 Classifieds model images
  db/seeds.js
  models/classifieds.js
  public/assets/js/post-classified.js
  views/classifieds_list_page.handlebars
  views/partials/classified-landing-page-partials/appliances.handlebars
  views/partials/classified-landing-page-partials/autos.handlebars
  views/partials/classified-landing-page-partials/baby_kid.handlebars
  views/partials/classified-landing-page-partials/bikes.handlebars
  views/partials/classified-landing-page-partials/clothes.handlebars
  views/partials/classified-landing-page-partials/electronics.handlebars
  views/partials/classified-landing-page-partials/furniture.handlebars
  views/partials/classified-landing-page-partials/lawn.handlebars
  views/partials/classified-landing-page-partials/music.handlebars
  views/partials/classified-landing-page-partials/sports.handlebars
  views/partials/classified-landing-page-partials/tickets.handlebars
  views/partials/classified-landing-page-partials/total_classifieds.handlebars
  views/partials/latest_classifieds_carousel.handlebars
  views/partials/post_class_partial.handlebars
Labels: back end

#191 Classifieds dynamic list
  data/hp-classifieds.json
  db/seeds.js
  models/classifieds.js
  public/assets/js/post-classified.js
  routes/html-routes.js
  views/classifieds_list_page.handlebars
  views/partials/classified-landing-page-partials/appliances.handlebars
  views/partials/classified-landing-page-partials/autos.handlebars
  views/partials/classified-landing-page-partials/baby_kid.handlebars
  views/partials/classified-landing-page-partials/bikes.handlebars
  views/partials/classified-landing-page-partials/clothes.handlebars
  views/partials/classified-landing-page-partials/electronics.handlebars
  views/partials/classified-landing-page-partials/furniture.handlebars
  views/partials/classified-landing-page-partials/lawn.handlebars
  views/partials/classified-landing-page-partials/music.handlebars
  views/partials/classified-landing-page-partials/sports.handlebars
  views/partials/classified-landing-page-partials/tickets.handlebars
  views/partials/latest_classifieds_carousel.handlebars
  views/partials/nav.handlebars
  views/partials/post_class_partial.handlebars
Labels: back end

#201 Adding image and category to home events
  views/partials/upcoming_events_carousel.handlebars
Labels: front end
